# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='starred_phrases',
            new_name='starred_terms',
        ),
    ]
