# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedict', '0007_auto_20160224_1306'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='terms',
            field=models.ManyToManyField(to='cedict.Term'),
        ),
    ]
