# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20160227_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 28, 15, 10, 59, 603339)),
            preserve_default=False,
        ),
    ]
