# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_text_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
    ]
