# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_text_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='translation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
