# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0010_remove_text_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='romanization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
