# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_phrase_romanization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phrases', models.ManyToManyField(to='texts.Phrase')),
            ],
        ),
    ]
