# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=255)),
                ('simplified', models.CharField(max_length=255)),
                ('pinyin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedict.Phrase')),
            ],
        ),
    ]
