# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedict', '0002_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
