# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedict', '0004_auto_20160131_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starred_phrases',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
