# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedict', '0006_auto_20160224_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='phrase',
            new_name='term',
        ),
    ]
