# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedict', '0007_auto_20160224_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='frequency',
            field=models.FloatField(default=0),
        ),
    ]
